## src/Acme/JobeetBundle/Resources/config/routing/job.yml
job:
    pattern:  /
    defaults: { _controller: "AcmeJobeetBundle:Job:index" }

#job_show:
#    pattern:  /{id}/show
#    defaults: { _controller: "AcmeJobeetBundle:Job:show" }
job_show:
    pattern: /{company}/{location}/{id}/{position}
    defaults: { _controller: "AcmeJobeetBundle:Job:show" }
    requirements:
        id: \d+

job_new:
    pattern:  /new
    defaults: { _controller: "AcmeJobeetBundle:Job:new" }

job_create:
    pattern:  /create
    defaults: { _controller: "AcmeJobeetBundle:Job:create" }
    requirements: { _method: post }

job_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AcmeJobeetBundle:Job:edit" }

job_update:
    pattern:  /{id}/update
    defaults: { _controller: "AcmeJobeetBundle:Job:update" }
    requirements: { _method: post|put }

job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AcmeJobeetBundle:Job:delete" }
    requirements: { _method: post|delete }
