Acme\JobeetBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255