AcmeJobeetBundle_job:
  resource: "@AcmeJobeetBundle/Resources/config/routing/job.yml"
  prefix: /job

AcmeJobeetBundle_homepage:
  pattern: /
  defaults: { _controller: AcmeJobeetBundle:Job:index }

AcmeJobeetBundle_category:
  pattern: /category/{slug}/{page}
  defaults: { _controller: AcmeJobeetBundle:Category:show, page:1 }

login:
  pattern: /login
  defaults: { _controller: AcmeJobeetBundle:Default:login }

login_check:
  pattern: /login_check
  ## Dont need to implement a _controller
  ## URL as the firewall will automatically catch and process any submitted to this URL

logout:
  pattern: /logout