AcmeJobeetBundle_job:
  resource: "@AcmeJobeetBundle/Resources/config/routing/job.yml"
  prefix: /job

AcmeJobeetBundle_homepage:
  pattern: /
  defaults: { _controller: AcmeJobeetBundle:Job:index }

AcmeJobeetBundle_category:
  pattern: /category/{slug}/{page}
  defaults: { _controller: AcmeJobeetBundle:Category:show, page:1 }